/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LiveRouteImport } from './routes/live'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DateTimelineRouteImport } from './routes/$date/timeline'
import { Route as DateClipsRouteImport } from './routes/$date/clips'

const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DateTimelineRoute = DateTimelineRouteImport.update({
  id: '/$date/timeline',
  path: '/$date/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const DateClipsRoute = DateClipsRouteImport.update({
  id: '/$date/clips',
  path: '/$date/clips',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/live': typeof LiveRoute
  '/$date/clips': typeof DateClipsRoute
  '/$date/timeline': typeof DateTimelineRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/live': typeof LiveRoute
  '/$date/clips': typeof DateClipsRoute
  '/$date/timeline': typeof DateTimelineRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/live': typeof LiveRoute
  '/$date/clips': typeof DateClipsRoute
  '/$date/timeline': typeof DateTimelineRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/live' | '/$date/clips' | '/$date/timeline'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/live' | '/$date/clips' | '/$date/timeline'
  id: '__root__' | '/' | '/live' | '/$date/clips' | '/$date/timeline'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LiveRoute: typeof LiveRoute
  DateClipsRoute: typeof DateClipsRoute
  DateTimelineRoute: typeof DateTimelineRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$date/timeline': {
      id: '/$date/timeline'
      path: '/$date/timeline'
      fullPath: '/$date/timeline'
      preLoaderRoute: typeof DateTimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$date/clips': {
      id: '/$date/clips'
      path: '/$date/clips'
      fullPath: '/$date/clips'
      preLoaderRoute: typeof DateClipsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LiveRoute: LiveRoute,
  DateClipsRoute: DateClipsRoute,
  DateTimelineRoute: DateTimelineRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
